package jary.note.nonblocking;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

/**
 * A very simple servlet, that just outputs a hard coded web page
 * Needless to say this is not a great way to do things, but this is just an example
 *
 * @author Stuart Douglas
 */
@WebServlet(name="SimpleServlet", urlPatterns = "/index.html")
public class SimpleServlet extends HttpServlet {

    @Override
    protected void doGet(final HttpServletRequest req, final HttpServletResponse resp) throws ServletException, IOException {
        resp.getWriter().write("<html><head><title>Simple Servlet</title>");
        resp.getWriter().write("<link rel=\"stylesheet\" type=\"text/css\" href=\"mypage.css\" media=\"screen\">");
        resp.getWriter().write("</head>");
        resp.getWriter().write("<body>");
        resp.getWriter().write("<h1>A simple servlet generated page</h1>");
        resp.getWriter().write("This page was generated by a servlet");
        resp.getWriter().write("</body>");
        resp.getWriter().write("</html>");
    }
}
